export default types = {
    CODESCANNERMINE: "CODESCANNERMINE",
    ALLCODESCANNERMINE: "ALLCODESCANNERMINE",
    ALLCODESCANNERMINEOTHER: "ALLCODESCANNERMINEOTHER",
    CODESCANNERMINEOTHER: "CODESCANNERMINEOTHER"
}